name: 'step-security/git-tag-action'
description: 'git tag to repository if the version is not tagged.'
author: 'step-security'
inputs:
  version:
    description: 'Git Tag version'
    required: true
  github_token:
    description: 'use secrets.GITHUB_TOKEN'
    required: true
  git_commit_sha:
    description: 'Git commit SHA'
    required: false
  git_tag_prefix:
    description: "prefix for git tag. Example) 'v'"
    required: false
    default: ""
  github_repo:
    description: 'GitHub repository path. Example) step-security/test'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'alert-octagon'
  color: 'blue'
